[package]
name = "command_slash_no_option"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.12", features = ["client", "framework", "model", "gateway"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"